version: '3'

services:
  postgres:
    image: 'postgres:9.6'
    # container_name: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=heroes
    ports:
      - '5432:5432'

  mongodb:
    image: mongo:4
    # container_name: 'mongodb'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=nimda
      - MONGO_INITDB_DATABASE=collection
    ports:
      - '27017:27017'

  mongoclient:
    # container_name: 'mongoclient'
    image: 'mongoclient/mongoclient'
    ports: 
      - '3000:3000'
  
volumes:
  postgres: {}
  mongodb: {}
  mongoclient: {}
