version: '3'

services:
  postgres:
    image: 'postgres:9.6'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=heroes
    ports:
      - '5432:5432'
  
volumes:
  postgres: {}

